vich_uploader:
    db_driver: orm
    metadata:
        auto_detection: true
        cache: file
        type: annotation
    mappings:
        prospects:
            uri_prefix: '%kernel.project_dir%/public/uploads/prospects'
            upload_destination: '%kernel.project_dir%/public/uploads/prospects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

