<?php

namespace App\Controller\Admin;

use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Field\EmailField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TelephoneField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use App\Entity\Prospect;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ProspectCrudController extends AbstractCrudController
{
    public function __construct(private string  $prospectDirectory)
{

}
    public static function getEntityFqcn(): string
    {

        return Prospect::class;
    }

    public function configureFilters(Filters $filters): Filters
    {
        //return parent::configureFilters($filters); // TODO: Change the autogenerated stub
        return $filters->add('nom');
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud->setEntityLabelInPlural('Prospects')
            ->setEntityLabelInSingular('Prospect')
            ->setDefaultSort(['id' => 'desc']);
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')->hideOnForm(),
            TextField::new('nom'),
            TextField::new('prenom'),
            EmailField::new('email'),
            TelephoneField::new('telephone'),
            TextEditorField::new('demandeDeDevis')->onlyOnForms(),
            TextField::new('file','Image')->setFormType(VichImageType::class),
            ImageField::new('image')->setBasePath('/uploads/prospects/')->onlyOnIndex(),


        ];
    }

    public function persistEntity(EntityManagerInterface $em, $entityInstance): void
    {
//        if (!$entityInstance instanceof Prospect) return;
//        $entityInstance->setImage($this->new(ImageField::class));

        parent::persistEntity($em, $entityInstance); // TODO: Change the autogenerated stub
    }
}
